name: Wien Tsang Architecture Blog
favicon: null
layout_spectrum: 0.5
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcdcd'
    - '#676566'
    - '#030303'
    - '#918e87'
    - '#2a2a2a'
  brandStrength: 0
  lightness: 0.504688965389505
  saturation: 0.48405627091415226
  rhythmicContrast: 0.6015586466528475
purpose: []
