name: Wien Tsang Architecture Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Architecture Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#93918c'
    - '#000000'
    - '#e6ddc9'
    - '#0c5778'
    - '#f0a557'
  brandStrength: 0
  lightness: 0.504688965389505
  saturation: 0.48405627091415226
  rhythmicContrast: 0.6015586466528475
purpose: []
